resolver: lts-16.9

packages:
  - .

extra-deps:
  - git: git@git.nejla.com:nejla-ab/common.git
    commit: 643a588e6dc303ef8d40491db4b4d2496ded490b
  -  hspec-wai-json-0.10.1@sha256:67b405c38f0a9e2771480c8d3ecd8aeb8d8776a35d3b2906cb1b76c9538617e4,1629

docker:
  enable: false
  image: nejla/haskell-build

nix:
  packages:
    - zlib
    - postgresql
