name: servant-example
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Nejla AB
license: BSD3
github: githubuser/servant-example
extra-source-files:
- README.md
library:
  source-dirs: src
  dependencies:
  - base >=4.7 && <5
  - aeson
  - servant-server
  - wai
  - warp
  - text
  - mtl

executables:
  servant-example-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-example
tests:
  servant-example-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - bytestring
    - servant-example
    - hspec
    - hspec-wai
    - hspec-wai-json
    - wai-extra
    - aeson
